version: "3.8"

services:
  db:
    ports:
      - 5432:5432
    env_file:
      - ./core_api/.env

  traefik:
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8081:8080"
    # Traefik has to be in all networks in order to resolve propery the containers it is trying to contact

  cache:
    ports:
      - 6379:6379
    volumes:
      - ./cache:/data

  core_api:
    build:
      target: dev
    env_file:
      - ./core_api/.env
    volumes:
      - ./core_api/.env:/app/core_api/.env
      - ./core_api/locales:/app/core_api/locales
      - ./core_api/src:/app/core_api/src
      - ./core_api/test:/app/core_api/test
      - ./core_api/prisma:/app/core_api/prisma
      - ./packages/core:/app/packages/core
      - ./core_api/uploads:/app/core_api/uploads

  front:
    build:
      target: dev
    volumes:
      - ./front/.env:/app/front/.env
      - ./front:/app/front
      - ./packages:/app/packages
